### ISSUE TITLE
JQuery Conflict with Django.ModelAdmin.autocomplete_fields

### ISSUE THREAD

**Issue by dennishylau** [erdem/django-map-widgets#100]
The problem is caused by the use of different jQuery files. Django relies on jquery.js (the one with ajax functions) to work, while map-widgets uses the jquery-3.3.1.slim.min.js (which has ajax stripped away). `autocomplete_fields` will thus stop working.

**Comment by SiddharthPant** [comment]
Facing the same issue. It will be good to have an option of skipping jquery import as its anyway loaded on the page because of some requirement or another. The default can be as it is now with an option to turn off the imports, until then on admin panel you have to choose between this application or having working autocomplete fields.

**Comment by SiddharthPant** [comment]
For now my temporary fix is to simply override the class and remove the slim from jquery and then everything works fine in the admin panel by using my custom widget.
```python
class CustomGooglePointWidget(GooglePointFieldWidget):
    @property
    def media(self):
        css = {"all": [minify_if_not_debug("mapwidgets/css/map_widgets{}.css")]}

        js = [
            "https://code.jquery.com/jquery-3.3.1.min.js",
            "https://maps.googleapis.com/maps/api/js?libraries=places&language={}&key={}".format(
                mw_settings.LANGUAGE, mw_settings.GOOGLE_MAP_API_KEY
            ),
        ]

        if not mw_settings.MINIFED:
            js = js + [
                "mapwidgets/js/jquery_class.js",
                "mapwidgets/js/django_mw_base.js",
                "mapwidgets/js/mw_google_point_field.js",
            ]
        else:
            js = js + ["mapwidgets/js/mw_google_point_field.min.js"]

        return forms.Media(js=js, css=css)

```

**Comment by yakky** [comment]
This is due to https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets

See linked PR for a proposal for resolution

**Comment by iMakedonsky** [comment]
same issue there.

**Comment by yakky** [comment]
@erdem great! thanks for fixing this :tada:
