### ISSUE TITLE
Only cities in widget

### ISSUE THREAD

**Issue by zyjswiadomielife** [erdem/django-map-widgets#102]
Hi, it's possible, to limit only to cities?

**Comment by erdem** [comment]
Yes, it possible. You need to check google place autocomplete documentation for limit by city option first, then update the map autocomplete widget options in `GooglePlaceAutocompleteOptions` settings attribute. 

https://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html#settings

Read properly this part of the documentation.
