### ISSUE TITLE
cannot import name six

### ISSUE THREAD

**Issue by juancrescente** [erdem/django-map-widgets#104]
In django 3.0:

ImportError: cannot import name 'six' from 'django.utils' (/Users/juan/Documents/manu/dev/yas/venv/lib/python3.7/site-packages/django/utils/__init__.py)

**Comment by catastrophix** [comment]
Related to deprecation of 'six' in Django 3 - [see this thread](https://stackoverflow.com/questions/59193514/importerror-cannot-import-name-six-from-django-utils)

**Comment by erdem** [comment]
I am not sure this widget will work on Django 3. I didn't get a chance test in a Django 3 stack, will update the readme about this.

**Comment by sasha00123** [comment]
Do you need any help with that?

**Comment by sasha00123** [comment]
I tried to install the following repo: https://github.com/a-ershov/django-map-widgets

**Comment by zoltankohalmy** [comment]
As I see it's already in the repo. When can we expect a new version to be released?

**Comment by erdem** [comment]
Hi Guys

I released the new version on PyPI. Update the topic if you see this issue again. 

`pip install django-map-widgets==0.2.3`

Thanks
