### ISSUE TITLE
This project support Django3.x?

### ISSUE THREAD

**Issue by rebirth00723** [erdem/django-map-widgets#111]

**Comment by erdem** [comment]
Did you get an error with Django 3.x? Or are you just asking a question?

Where is the context of your issue?

**Comment by rebirth00723** [comment]
I want to use this project in DJango3.x
But according to your compilation report, it only runs on Django 2.x
Want to know if there is support for Djnago3.x?

**Comment by erdem** [comment]
The tests are passed in Django 3.0 environment so, it should work.
