### ISSUE TITLE
Dosen`t work settings from settings.py.

### ISSUE THREAD

**Issue by zelds** [erdem/django-map-widgets#12]
Hi. This is my settings. But it`s dosent work. When i comment the map still works.
`MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        ("size", "320x320"),
    ),
    "GOOGLE_MAP_API_KEY": "KEY",
}`
And one more question. How i can make map responsible ?

**Comment by erdem** [comment]
Hi @zelds 

Sorry, I didn't understand your issue. Did you check the example project on the repo ? 
https://github.com/erdem/django-map-widgets/blob/master/example/example/settings.py#L150

The map responsive by default.
