### ISSUE TITLE
Undefined geocoding response object "place" when triggering "google_point_map_widget:marker_change"

### ISSUE THREAD

**Issue by aatifkhan-git** [erdem/django-map-widgets#125]
I don't seem to get the "place" object in the console logs when marker_change is triggered. Others logs are fine. Can't seem to figure out why that is. I was hoping to capture more details from the response and display them as well. Any help will be appreciated. Thanks. 

```
$(document).on("google_point_map_widget:marker_change", function (e, place, lat, lng, locationInputElem, mapWrapID) {
    console.log(place); // Google geocoding response object
    console.log(locationInputElem); // django widget textarea widget (hidden)
    console.log(lat, lng);  // changed marker coordinates
    console.log(mapWrapID); // map widget wrapper element ID
});
```
Env: 
django-map-widgets 0.3.2
django 2.2.24
Python 3.7

**Comment by adonig** [comment]
Is there a workaround besides doing a reverse geocode request?

**Comment by kptac** [comment]
it works with `google_point_map_widget:place_changed` event, so hopefully that should help. "marker_change" doesn't have the place object.

**Comment by erdem** [comment]
I am late to cover this one but I have fixed the place object bind issues in the new release. (`0.4.0`)

https://pypi.org/project/django-map-widgets/0.4.0/
