### ISSUE TITLE
mapCenterLocation dosent work.

### ISSUE THREAD

**Issue by zelds** [erdem/django-map-widgets#13]
But center of the map center is still in Denver. The same with custom style. 

settings.py
```
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        ("mapCenterLocation", [57.7177013, -16.6300491]),
    ),
    "GOOGLE_MAP_API_KEY": "KeyHere",
}
```

**Comment by erdem** [comment]
Hi @zelds  

The `mapCenterLocation` feature is worked for me. I don't understand your issue exactly. You should give more detail about the issue. 

Is there any error on the browser Console?

**Comment by zelds** [comment]
Just one warning 

> Use of Mutation Events is deprecated. Use MutationObserver instead.

**Comment by erdem** [comment]
I think, your issue is not related with the map widget. I tested all feature on the map widgets and I didn't see your problem. If you think the issue is related with `django-map-widgets`, post your map widget settings and usage.

Thanks

**Comment by AllanZambrano** [comment]
Hey! I'm having this issue, it always shows coordinates (0,0). 
 Btw, I'm using Django 2.2

Settings: 
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        ("mapCenterLocation", [57.7177013, -16.6300491])
    ),
"GOOGLE_MAP_API_KEY": "<KEY>"
} 

And it shows the following: 
![1](https://user-images.githubusercontent.com/18707287/61762229-a7ed4800-ada7-11e9-9f7a-9e5218ca373c.PNG)

**Comment by AllanZambrano** [comment]
So, I did some testing today and I think it's a problem with Windows, tried the same settings on Ubuntu and worked perfectly.

**Comment by erdem** [comment]
I didn't test this scenario but, the issue could be related to longitude and latitude position in the settings array.
