### ISSUE TITLE
Form field errors are not shown

### ISSUE THREAD

**Issue by pawelad** [erdem/django-map-widgets#132]
Hi!

First of all, thanks a lot for creating this, it works really well.

One problem I'm having, I believe there's no support for Django form field errors to be shown in the template.

So for example, if the field that uses one of the Google Maps widget is required, but isn't filled in, the form fails on `is_valid()` and produces `form.errors` but those aren't shown anywhere in the template.

Is that to be expected or am I doing anything wrong?

**Comment by erdem** [comment]
The forms are working fine with the widgets, please check the demo project if you still facing the same issue.
