### ISSUE TITLE
The map doesn't appear and ScrollWheel  zooming settings

### ISSUE THREAD

**Issue by VLunaa** [erdem/django-map-widgets#134]
![imagen](https://user-images.githubusercontent.com/70333868/208219385-885a5ba9-81bb-4ece-aef3-1435e670006c.png)

I followed all the steps of the documentation to the letter, could it be an error in my api key?, the three required apis are already added.

Forms:
![imagen](https://user-images.githubusercontent.com/70333868/208219467-c9baaae2-ff0e-4de9-979f-e835fcbb1f0e.png)

Template:
![imagen](https://user-images.githubusercontent.com/70333868/208219483-92568f44-dcd7-4649-9fa3-45a6b9cc8fd4.png)

I'm using django 4.0.2.

Settings:
![imagen](https://user-images.githubusercontent.com/70333868/208220977-103a9ccf-a55b-4aed-8105-fbc46e817602.png)

**Comment by VLunaa** [comment]
These errors are displayed on the console.
![imagen](https://user-images.githubusercontent.com/70333868/208224153-95c1e6c7-d09d-4dba-b164-322e496603b8.png)

**Comment by VLunaa** [comment]
> The issue may be related to the jQuery version that you used. I have used `2.x` jquery while I am developing the widgets.
> 
> Take a look at the demo project to see if that helps.
> 
> https://github.com/erdem/django-map-widgets/tree/master/demo/

Thanks, it's working now. Do you know any way to make the map zoom move with the scroll?
And thanks for this great job, by the way.

**Comment by erdem** [comment]
@VLunaa 

I disabled the scroll wheel zooming functionality during the initial development, it was messing up the actual page scrolling when the mouse cursor came over the map component. It was so a long time ago, didn't notice that settings were hardcoded until reading your last message. 

However, I just released the new version which includes `scrollWheel` settings. Upgrade the PyPI package in your stack and set `scrollWheel` as `True` in the django settings.  

You are welcome!


**settings.py**
```python
GOOGLE_MAP_API_KEY = os.getenv('GOOGLE_MAP_API_KEY', None)
MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', None)
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        ("mapCenterLocation", [51.5073509, -0.12775829999998223]),
        ("markerFitZoom", 11),
        ("GooglePlaceAutocompleteOptions", {'componentRestrictions': {'country': 'uk'}}),
        ("streetViewControl", False),
        ("scrollWheel", True)
    ),
    "MapboxPointFieldWidget": {
        "access_token": MAPBOX_API_KEY,
        "mapOptions": {
            "zoom": 10,
            "center": (51.515618, -0.091998)
        }
    },
    "GOOGLE_MAP_API_KEY": GOOGLE_MAP_API_KEY
}

```
