### ISSUE TITLE
GooglePointFieldInlineWidget doesn't work with Django 4.2.2

### ISSUE THREAD

**Issue by isarota** [erdem/django-map-widgets#141]
`row` and `prefix` parameters come `undefined` [here](https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/static/mapwidgets/js/mw_google_point_field_generater.js#L9), therefore when I click `Add another ...` in Django admin, required map doesn't appear.

**Comment by erdem** [comment]
Hi @isarota 

I have published a new version with your fix, nice one!  

Thank you for your contribution.

https://pypi.org/project/django-map-widgets/0.4.2/
