### ISSUE TITLE
Map doesn't show in django admin?

### ISSUE THREAD

**Issue by luvwinnie** [erdem/django-map-widgets#145]
I'm using this package, and it doesn't shows the map widget on my admin page with these errors.

settings.py
```
GOOGLE_MAP_API_KEY = os.getenv('GOOGLE_MAP_API_KEY', None)
MAPBOX_API_KEY = os.getenv('MAPBOX_API_KEY', None)
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 12),
        ("mapCenterLocation", [xxxxx, xxxx]),
        ("markerFitZoom", 11),
        ("GooglePlaceAutocompleteOptions", {'componentRestrictions': {'country': 'jp'}}),
        ("streetViewControl", True),
        ("scrollWheel", True)
    ),
    "MapboxPointFieldWidget": {
        "access_token": MAPBOX_API_KEY,
        "mapOptions": {
            "zoom": 10,
            "center": (xxxx, xxxx)
        }
    },
    "GOOGLE_MAP_API_KEY": GOOGLE_MAP_API_KEY


}
```

<img width="645" alt="Screenshot 2024-04-17 at 12 36 16" src="https://github.com/erdem/django-map-widgets/assets/13714992/73d6a1b6-a3ea-45fc-ac6c-7e1508de5ce1">
<img width="964" alt="Screenshot 2024-04-17 at 12 36 47" src="https://github.com/erdem/django-map-widgets/assets/13714992/7733f5a0-085a-4fe6-bea8-ed73403b6100">

how can I fix this?

**Comment by erdem** [comment]
it works for me, you may get this error because of your `MAP_WIDGETS ` settings, try it with the default settings.
