### ISSUE TITLE
Feature request: Leaflet Searchbox

### ISSUE THREAD

**Issue by ShmuelTreiger** [erdem/django-map-widgets#153]
Is there a reason you didn't integrate a leaflet searchbox? Based on cursory googling it seems [rather simple](https://www.youtube.com/watch?v=rEa_S_HiKxs), though I'm sure there's a reason you haven't (perhaps simply time constraint).

**Comment by erdem** [comment]
It is not as simple as it seems. I looked at this project a few months ago and didn't find it to be a good solution. The maintenance is poor, and the demos were outdated. There weren't even compiled JS files from the latest TypeScript version in the master branch. I tried setting up the project locally, but it didn't work for me either.

I would like to add geocoding to the leaflet interactive widget, but not with this project current version. If you could develop a working demo for the leaflet widget with your shared component, go ahead and hit that create pull request button.

**Comment by josx** [comment]
Maybe it is easier to use this lib https://github.com/smeijer/leaflet-geosearch/
