### ISSUE TITLE
Django 5.1 migration

### ISSUE THREAD

**Issue by martinlehoux** [erdem/django-map-widgets#155]
The [Django 5.1 release](https://docs.djangoproject.com/en/5.1/releases/5.1/#features-removed-in-5-1) removes `map_width` and `map_height`. I get an exception while accessing the admin page `AttributeError: 'GooglePointFieldWidget' object has no attribute 'map_width'`.

Is the solution as easy as removing these two fields from `BasePointFieldMapWidget.__init__`? At least it works for me

**Comment by erdem** [comment]
Which version are you using? I remember solved this issue in earlier releases.

**Comment by martinlehoux** [comment]
Ok i'm sorry I supposed we had the latest, but of course not the case... I was on 0.4.2

Works like a charm, thanks!
