### ISSUE TITLE
[class^="icon-"], [class*=" icon-"] CSS selector clashes with existing CSS

### ISSUE THREAD

**Issue by dnmellen** [erdem/django-map-widgets#18]
Hi, I'm using django-jet as Django admin theme and when I use django-map-widgets all my other icons dissapear because a collision in CSS selectors.

It would be nice that the CSS selectors in django-map-widgets only affect the map widget itself.

This can be easily solved by adding `.mw-wrap` to the selector in `map_widgets.css`:

```css
.mw-wrap [class^="icon-"]:before, .mw-wrap [class*=" icon-"]:before {
    font-family: "fontello";
    font-style: normal;
    font-weight: normal;
    ...
```

**Comment by dnmellen** [comment]
I noticed this is just fixed in master branch.

**Comment by erdem** [comment]
@dnmellen FYI, the `0.1.8` version submitted to PyPI. You can install from pip instead of master branch.

Thanks.
