### ISSUE TITLE
Translation don't work

### ISSUE THREAD

**Issue by izaguerreiro** [erdem/django-map-widgets#19]
My settings are configured with language-code pt-BR, but the texts of the map don't translate.

**Comment by erdem** [comment]
Hi @izaguerreiro 

The package support only English and Russian languages. if you can send a pull request with the pt-BR local file, I can accept your pull request.

You can see [here](https://github.com/erdem/django-map-widgets/tree/master/mapwidgets/locale
) other languages locale files. 

Thanks

**Comment by izaguerreiro** [comment]
Hi @erdem, 

I forked the repository and I will send pull request with pr-BR local file.

Thank you for support.

**Comment by izaguerreiro** [comment]
How do I compile locale file? Because I did `django-admin compilemessages`, but the translation don't work.

**Comment by izaguerreiro** [comment]
I sent the pull request

**Comment by mykljohn** [comment]
I have it in Spanish if you're interested.

**Comment by erdem** [comment]
@mykljohn yeah sure, just send a pull request for the master branch. 
Thanks.
