### ISSUE TITLE
map marker events not working

### ISSUE THREAD

**Issue by nakul-sayone** [erdem/django-map-widgets#21]
`$(document).on("google_point_map_widget:marker_create", function (e, lat, lng, locationInputElem, mapWrapID) {
    console.log(locationInputElem); // django widget textarea widget (hidden)
    console.log(lat, lng); // created marker coordinates
    console.log(mapWrapID); // map widget wrapper element ID
});
`
I tried the above code following the [docs](http://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html)  , I am unable to trigger the event. Please do help?

**Comment by erdem** [comment]
@nakul-sayone Which jQuery version you are using?

**Comment by nakul-sayone** [comment]
jquery  v2.2.3

**Comment by erdem** [comment]
I tested the marker triggers with `jQuery v2.2.3` and it is worked for me. Check your JS implementation it might be a different issue.

Check the example project here:
https://github.com/erdem/django-map-widgets/blob/master/example/templates/cities/form.html#L6 

Thanks

**Comment by nakul-sayone** [comment]
Hi @erdem  it is working in the front end. I need the events in the backend admin page. I tried with a lot of combinations but it doesn't works. could you please walk me through this?  its kind of urgent

**Comment by erdem** [comment]
Hi @nakul-sayone

I also tested the triggers on Django admin and it is worked too. Did you notice Django admin jQuery namespace? Django admin using a different namespace for built-in jQuery. (`django.jQuery`)

You must read this documentation first.
https://docs.djangoproject.com/en/1.10/ref/contrib/admin/javascript/

Here is my Django admin implementation: 

```javascript
{% extends 'admin/change_form.html' %}
{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script type="text/javascript">
        (function($) {
            $(document).on("google_point_map_widget:marker_create", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng); // created marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("google_point_map_widget:marker_change", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // changed marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            });

            $(document).on("google_point_map_widget:marker_delete", function (e, lat, lng, locationInputElem, mapWrapID) {
                console.log(locationInputElem); // django widget textarea widget (hidden)
                console.log(lat, lng);  // deleted marker coordinates
                console.log(mapWrapID); // map widget wrapper element ID
            })
        })(django.jQuery);
    </script>
{% endblock %}
```

if your Django version under `1.9`, you can also override `extrahead` block on admin templates.

Thanks.
