### ISSUE TITLE
[Question] Capturing the Address field

### ISSUE THREAD

**Issue by mykljohn** [erdem/django-map-widgets#22]
Hi, Love map-widget.  Nice and easy to implement and looks good.

I would like to capture what was entered in the Address Field in a field in my MySQL database.  Any help with that?  Cheers, Mykl

**Comment by erdem** [comment]
Hi Myki

The widgets are working with only PostGIS point fields. If you want store entered address, you must use a separate text field for that.

**How to capture the entered address?**

In this case, the best approach would implement a JS trigger handler for the Google place autocomplete actions. Like marker triggers, check Javascript API section in this [document page](http://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html#usage).

Unfortunately, there is no any JS trigger implementation for entered addresses at the moment. But, I think it would be nice to have for the widgets. Probably, I will add this feature to the package soon.

If you are looking a quick solution for now, maybe you can listen to autocomplete input change event, and then you can get the address from the input value.

Thanks.

**Comment by mykljohn** [comment]
I'm not well versed in java, but I'll see what I can do.  cheers

**Comment by mykljohn** [comment]
Woohoo!  I found this https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

**Comment by erdem** [comment]
Hi @mykljohn 

I implemented Google geocoding service support in `v0.1.9` version. You can check [this page](http://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html) for documentation. 

Thanks
