### ISSUE TITLE
Widget not showing in Admin

### ISSUE THREAD

**Issue by davidkrcil** [erdem/django-map-widgets#23]
Hello, I run your example from git. In admin on add/edit place page I can see only 3 text fields instead of map widget. What I am doing wrong? Thanks for any help.
David

I spent all day trying to run some of google map widget on admin. No result :-(

Mac OS, django.VERSION
(1, 11, 0, u'final', 1)
Safari

**Comment by erdem** [comment]
The widget is working you must have an different issue.

Did you run `python manage.py collectstatic` ?

**Comment by davidkrcil** [comment]
Thanks. I am runing in debug so static have not set still. I will try to play with it.

**Comment by davidkrcil** [comment]
I perforemed python manage.py collectstatic. No change. It is strange if I check the HTML of admin page - I can't see anything related to the map widget:

<div class="form-row field-location">
            
            
                <div>
                    
                    
                        <label for="id_location_0">Location:</label>
                        
                            <input type="text" name="location_0" data-geo="formatted_address" class="places" id="id_location_0">

<input type="text" name="location_1" data-geo="lat" class="places" id="id_location_1">

<input type="text" name="location_2" data-geo="lng" class="places" id="id_location_2">
                        
                    
                    
                </div>
            
        </div>

**Comment by davidkrcil** [comment]
Ahh you already closed the issue ... Ok do not wory. I will try to resolve on my own.

**Comment by erdem** [comment]
@davidkrcil The package static files can not load. You should check your project settings. Make sure the project `STATIC_URL` is working. Probably, you are missing some points on project settings or root`urls.py` file. Check the Django documentation.

https://docs.djangoproject.com/en/1.11/howto/static-files/
