### ISSUE TITLE
DjangoGooglePointFieldWidget is not defined

### ISSUE THREAD

**Issue by gabrielpiccolo4** [erdem/django-map-widgets#26]
Guys, sorry to trouble you but I've followed the instructions in the docs and when my browser renders the page the debugger says `'ReferenceError: DjangoGooglePointFieldWidget is not defined'` in the following line: `new DjangoGooglePointFieldWidget(mapWidgetOptions);`. 

My template already has jQuery and Bootstrap setted, and inside Django settings the app `'mapwidgets',` is placed, I don't know if this is an issue? The following image shows how the page is displayed:
![image](https://user-images.githubusercontent.com/10145361/26996329-08f0fe52-4d48-11e7-948c-3f7258849563.png)

**Comment by erdem** [comment]
Hi @gabrielpiccolo4 

It seems the static files not loaded in your project. Did you call `python manage.py collectstatic`? 

You must copy the third-party packages static files into the `STATIC_ROOT` with collectstatic management command.

**Comment by gabrielpiccolo4** [comment]
Hey @erdem thanks for answering back! 

Sorry I missed this part of the tutorial. I ran the command `collectstatic` and Django successfuly coppied all the files, but the browsers yet say `Reference Error`. 

The strange thing is that when I create the field with `GoogleStaticMapWidget` it loads the image from the app `<img src="/static/mapwidgets/images/no-map-image.png" class="no-map-image">` from the static folder, and all the js files are in there.

**Comment by erdem** [comment]
That image is a placeholder image for blank geo point fields. There is no input option for `GoogleStaticMapWidget`. The static widgets are read-only. If you need to input for geo point fields, you have to use `GooglePointFieldWidget`. 

The static files issue must be fixed after the `collectstatic` command. If it is not sorted out, post your [Django static app](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/) configuration in the project settings file.

Thanks

**Comment by gabrielpiccolo4** [comment]
Hi @erdem, I tried some things and none worked... I created a new app to test and the problem persists. Maybe you can help me, my settings.py related to static-files are as follows:

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

I'm just wondering, (please note I'm studying the framework yet) the `collectstatic` isn't used just when the app is ready to deploy? 'Cause I'm yet using django's run server to test it.

Just a question, I'm not using PostgreSQL, I'm using MySQL, and my models ain't using the PointField, but CharFields, not sure if this can cause that error?

Thanks for helping me,
Gabriel

**Comment by erdem** [comment]
Hi @gabrielpiccolo4 

I didn't try the widget with `CharField`, but it should work.

If you are working on the development mode, you must add static files serving view for the `urls`. I think you missed that part in your project.

Check out the links below:

https://docs.djangoproject.com/en/1.11/howto/static-files/#serving-static-files-during-development

https://github.com/erdem/django-map-widgets/blob/master/example/example/urls.py#L13

Thanks.

**Comment by gabrielpiccolo4** [comment]
I missed this part in this new project I created, unfortunately no luck =(
Maybe is it something in my Windows? Could you try to run `python manage.py runserver` on the project below? The index page is using the widget.

[django_1-11_maps-widget2.zip](https://github.com/erdem/django-map-widgets/files/1078204/django_1-11_maps-widget2.zip)

Thanks Erdem, again, sorry to trouble you

**Comment by erdem** [comment]
I understand the issue. Your template doesn't have `{{ form.media }}` variable. Put `{{ form.media }}` variable to `<head>` tag or end of the `<body>` tag in your `index.html`. Then it should work.  

Like here: 
https://github.com/erdem/django-map-widgets/blob/master/example/templates/cities/form.html#L4

I missed this part when I was writing instructions. I will update the document for that. 

Thank you for noticing me about that.

**Comment by gabrielpiccolo4** [comment]
It worked! Thanks @erdem!
