### ISSUE TITLE
Support for OpenStreetMap

### ISSUE THREAD

**Issue by jeasoft** [erdem/django-map-widgets#28]
Hi! I came across this package for the promise to use it with Openstreetmaps, but it hasn't support for this now. Are you planning you planning to implement this soon?
Greetings!

**Comment by erdem** [comment]
HI @jeasoft 

Thank you for your contribution.

Yes, I am planning to add OpenStreetMap support, but to be honest, I can't implement soon. I might be release in August. 

If you want to send a pull request for OpenStreetMap support, you are welcome. There is no too much work on backend side. We need to implement a JS class for the new widget. If you require more information about the codebase, just let me know. 

Thanks

**Comment by jeasoft** [comment]
Thank you!
