### ISSUE TITLE
Map image is not found

### ISSUE THREAD

**Issue by brianbola90** [erdem/django-map-widgets#33]
The static map widget is rendering with message "the image map is not found" 
I don't know what form field to use for the city.
Where am I going wrong?

```python
class JobForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'title'}))
    location = forms.CharField(widget=GooglePointFieldWidget)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label=None, widget=forms.Select())
    class Meta:
        model = Job
        fields = ('title','city', 'location', 'category')
        widgets = {
            'city': GoogleStaticMapWidget
        }
```

**Comment by erdem** [comment]
I guess this is a [Django Static App](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/) configuration issue. Check your static app settings.

https://github.com/erdem/django-map-widgets/issues/26
Also, you can check this conversation, it might be helpful. 

Thanks
