### ISSUE TITLE
How to use in template?

### ISSUE THREAD

**Issue by trDjango** [erdem/django-map-widgets#38]
Hello Erdem;
how can I show the map in the template? if you have template tags, how can you share?by the way if you know turkish; çok iyi bir iş çıkarmışsın :)

**Comment by erdem** [comment]
Hello 

If you need to use the widget in a view template, you must have a form implementation. You can find instructions in the [documentation](http://django-map-widgets.readthedocs.io/en/latest/index.html) also you can check the example project in the repo. 

Teşekkürler :)
