### ISSUE TITLE
CSS styling overrides bootstrap theming

### ISSUE THREAD

**Issue by MichaelAnckaert** [erdem/django-map-widgets#4]
The included CSS styles override the bootstrap theming and causes problems for existing applications. 

If i create a pull request that renames the django-map-widgets css styles will it be accepted? 

Proposed css class prefix: mw- 

For example
rename .btn-default to .mw-btn-default

**Comment by erdem** [comment]
Hi Micheal 

I just realised after your ticket, bootstrap button CSS classes doesn't have `.mw-wrap` parent selector. 

Normally I writing `.mw-wrap` selector for every child CSS class definition. Like `mw-wrap .icon-location`.

I think, your idea is more useful fixed the bootstrap CSS conflict. If you send a pull request for this issue. That's will be great.

Thank you.

**Comment by erdem** [comment]
#6
