### ISSUE TITLE
Map inside hidden fieldset

### ISSUE THREAD

**Issue by manuelcua** [erdem/django-map-widgets#40]
The Map does not initialize correctly in the Admin if it's inside a hidden fieldset.

Great widget by the way!

**Comment by erdem** [comment]
@manuelcua I fixed this issue but I didn't push to PyPI yet. I will publish the new release soon. 
You can install the latest changes from master branch for now. 

`pip install git+git://github.com/erdem/django-map-widgets.git`

Would be good if you can test the changes on your environment.

Thank you for your contribution.
