### ISSUE TITLE
GooglePointFieldInlineWidget not working

### ISSUE THREAD

**Issue by teror4uks** [erdem/django-map-widgets#42]
I want use django-map-widgets in inline style. 
```
class TransportAdminForm(forms.ModelForm):

    class Meta:
        fields = (
            "coordinate",
            "destination",
            'type_transport',
            'date_loading',
            'valid',
            'is_published'
        )
        widgets = {
            'coordinate': GooglePointFieldInlineWidget,
        }


class TransportAdminStackedInline(admin.StackedInline):
    model = Transport
    form = TransportAdminForm
    extra = 0
    # formfield_overrides = {
    #     models.PointField: {"widget": GooglePointFieldInlineWidget}
    # }


@admin.register(Carrier)
class CarrierAdmin(admin.ModelAdmin):
    form = CarrierAdminForm
    list_display = ('company_name', 'is_published')
    list_display_links = ('company_name',)
    list_editable = ('is_published', )
    inlines = [TransportAdminStackedInline]
```
but it does not works, I get empty map without scrolls, point and opportunity write and change coordinates. It seems like this:
![image](https://user-images.githubusercontent.com/10071749/32597937-4f6c5cfe-c549-11e7-8c6b-30666e43d912.png)

**Comment by teror4uks** [comment]
more info: I use django-jet admin

**Comment by erdem** [comment]
Thank you for your contribution. @teror4uks 

I tested `GooglePointFieldInlineWidget` with only itself, and it worked. I implemented a Django admin class as like yours, and that worked as well. I didn't reproduce your issue. It might be a conflict with django-jet. Make sure mapwidgets static files copied your `STATIC_ROOT` after called `collecstatic` command.
