### ISSUE TITLE
GoogleMaps API Key for localhost projects

### ISSUE THREAD

**Issue by MoCuishla1983** [erdem/django-map-widgets#43]
I am a web developer who is doing a personal project and this project is in the development phase, which is why I am still working in a local environment (localhost). I have a GoogleMaps API Key created, but for its use it is necessary to create credentials to the URLs that are going to make use of the API key. The problem comes when a localhost address is not addressable from the Key API.
That is why I am writing to you to ask you how I can do to be able to use your widget in a local environment. Is there any way?
Thank you very much for providing such a useful widget to facilitate the use of the Google Maps API. A cordial greeting.

**Comment by erdem** [comment]
Hi @MoCuishla1983 

The API Keys should work with `localhost`. As far as I know, Google has no restriction for `localhost` domain. I just tested my API key, and It worked on my local. 

https://developers.google.com/maps/documentation/javascript/get-api-key
You might get a different type of API Key. You can generate a new Google Map API Key on this page.

Thanks.
