### ISSUE TITLE
Map and Satellite buttons disappear when collapse class is used in admin

### ISSUE THREAD

**Issue by dennereed** [erdem/django-map-widgets#45]
In the admin view of the GooglePointFieldWidget the Map and Satellite buttons are not visible when fieldsets are set with the collapse class. For example:
fieldsets = [
...
        ('Provenience', {
            'fields': [
                       ('easting', 'northing'),
                       ('geom',)],
            'classes': ['collapse'],
        })
    ]

They reappear when collapse is removed.  I'm using django 1.11 with python 3.6.2.  Not sure if it happens with the other widgets as well.

**Comment by erdem** [comment]
Hi @dennereed 

This issue must be relevant to your google map settings. I tested the widget in an admin collapse and the buttons show up. Which Django version are you using?

![collapse_ss](https://user-images.githubusercontent.com/1518272/35487592-07d41fce-0475-11e8-8f88-37e71448b3ce.png)

**Comment by dennereed** [comment]
Hi and thanks for the reply on this issue,
I’m using Django 1.11 with python 3.6.

Thanks,
Denné

-- 
Denne Reed
Sent with Airmail

On January 28, 2018 at 1:49:13 PM, Erdem Ozkol (notifications@github.com)
wrote:

Hi @dennereed <https://github.com/dennereed>

This issue must be relevant to your google map settings. I tested the
widget in an admin collapse and the buttons show up. Which Django version
are you using?

[image: collapse_ss]
<https://user-images.githubusercontent.com/1518272/35487592-07d41fce-0475-11e8-8f88-37e71448b3ce.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/erdem/django-map-widgets/issues/45#issuecomment-361099153>,
or mute the thread
