### ISSUE TITLE
Change default GMap options

### ISSUE THREAD

**Issue by emibcn** [erdem/django-map-widgets#47]
Hello!
I'm using this library on one of my projects and I'd like to enable `scrollWheel` on the generated maps. I have tried to do it dynamically after map is created, but I haven't found any way to access to the map object saved at `DjangoGooglePointFieldWidget.map`, as it is created inside anonymous closures. Is it possible to add some method to be able to change map options, either at creation time or dynamically? For better pluggable system, I suppose a dynamic way to get map object should be the better option. This way, one could add layers, markers, bubbles and whatever GMap offers.

Thanks a lot in advance!!

**Comment by erdem** [comment]
Hi @emibcn 

Thank you for your contribution! 

I am planning to add all map options to global settings in next release. So after that, you will be able to set all map options in django settings file. Recently, you can set only `zoom`, `GooglePlaceAutocompleteOptions ` and `markerFitZoom` options in settings. 

Also, I accepted your pull-request. I believe, it is not the best practice solve this issue but its something useful. I will close this issue after I released the new version.
