### ISSUE TITLE
Can not hide infowindow

### ISSUE THREAD

**Issue by Rajankumarqw** [erdem/django-map-widgets#50]
I have implemented form like this

> widgets = {
>             'point': GooglePointFieldWidget,
>             'address': forms.HiddenInput
>         }
But i have to hide info window, how i can do this can any one help me please.

**Comment by erdem** [comment]
There must be a GMap option for that; you need to set when the map initialising. Unfortunately, the current version doesn't have full support for GMap options. I am planning to add in next release. 

https://github.com/erdem/django-map-widgets/issues/47
https://github.com/erdem/django-map-widgets/pull/48

This workaround may help to fix your issue.

**Comment by Rajankumarqw** [comment]
ok Thanks for this help #erdem.
