### ISSUE TITLE
suggestion: dynamically localizing the map + dynamically center the map

### ISSUE THREAD

**Issue by michaelhjulskov** [erdem/django-map-widgets#55]
A few suggestions for the mapwidget future versions.
1. a way to dynamically localize the map. maybe by setting a language variable 'mapwidget_language' in the view (https://developers.google.com/maps/documentation/javascript/localization).  or maybe add a javascript example to the documentation, how to change map language.

2. a way to dynamically (or automaitacally) center the map (if no point is selected) by guessing the user location from IP address or something smarter. or by setting a 'mapwidget_center' variable in the view. or maybe add a javascript example to the documentation, how to center the map.

I hope you understand my suggestion :)

Thank You

**Comment by erdem** [comment]
Hi @michaelhjulskov 

I noted these suggestions and I will add the project milestones. These features may never implement by me. I don't have much time for this project anymore. I am only fixing Django compatibility issues when I got a time. If you want to implement these features for the project, your pull requests are welcome. :) 

Thanks for the feedback!

**Comment by michaelhjulskov** [comment]
You're  welcome.
Im close to solving it. As soon as i solved it, i will gladly share it.
I have opened a question on stackoverflow about the part that i cant solve:
https://stackoverflow.com/questions/48986691/how-to-add-markers-and-center-map-in-signup-form-django-map-widget

**Comment by erdem** [comment]
Hey, I updated the StackOverflow topic.
