### ISSUE TITLE
Zoom in Settings does not work

### ISSUE THREAD

**Issue by pwfraley** [erdem/django-map-widgets#59]
My Settings:

`MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 1),
        ("markerFitZoom", 12)
    ),
    "GOOGLE_MAP_API_KEY": GOOGLE_MAPS_API_KEY
}
`
No matter what I set the zoom to (tried 1 thru 15), I am always completely zoomed in.  Also tried changing the markerFitZoom but it does not make a difference.

**Comment by Michelk12** [comment]
I have the same problem. :-/
My settings:

```
MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 8),
        ("mapCenterLocationName", "toulouse"),
        ("markerFitZoom", 4),
    ),
    "GOOGLE_MAP_API_KEY": GOOGLE_MAP_API_KEY
}
```

`mapCenterLocationName` works properly but `zoom` or `markerFitZoom` doesn't work.
I tried to change the zoom value in JS or template without success

**Comment by ekimia** [comment]
any clue how to fix this? Would be happy to submit a PR.

**Comment by hlodver** [comment]
I added a pull request fixing the issue

**Comment by erdem** [comment]
@hlodver I merged the PR to master. Thank you for your contribution.

**Comment by Michelk12** [comment]
I left Google and I'm now using OpenStreetMap
