### ISSUE TITLE
get complete response from geocoding in javascript triggers

### ISSUE THREAD

**Issue by stitch** [erdem/django-map-widgets#74]
Hi,

The javascript triggers should be able to get the full response from geocoding an address (if that process is happening). The google geocoder often includes extra information such as country: this can be valuable for other values in the form.

Currently a place object is given, which seems to be a shorthand or partial response. (in 0.1.9 the lat value is given in the place parameter, the place object is not sent at all).

Would such a feature add value to the widget?

Regards,
Elger

**Comment by erdem** [comment]
Hi Elger,

I would like to add this patch, but it is really hard to get a new release for this project at the moment. Bunch of things waiting in `v0.2.0` branch to release. I have to deal with them first. 

The best thing you need to do in this case, you need to fork the project and update the related methods then you can install your version from your Github repository. 

like this: 
`pip install git+git://github.com/<your-github-username>/django-map-widgets.git@master` 


https://github.com/erdem/django-map-widgets/blob/849c00235d32f5339c5fdcf44a19ee61fd68425e/mapwidgets/static/mapwidgets/js/django_mw_base.js#L192

You need to update this method passing geocoding full response to JS triggers. Feel free to send your changes within a pull-request for the project. 

Thanks

**Comment by erdem** [comment]
The geocoding handler binding the full response object to the JS triggers in `v0.2.0` version. 

```javascript
$(document).on("google_point_map_widget:marker_create", 
    function (e, place, lat, lng, locationInputElem, mapWrapID) {
        console.log(place); // Google geocoding response object
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng); // created marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
});

$(document).on("google_point_map_widget:marker_change", 
    function (e, place, lat, lng, locationInputElem, mapWrapID) {
        console.log(place); // Google geocoding response object
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng);  // changed marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
});

$(document).on("google_point_map_widget:marker_delete", 
    function (e, lat, lng, locationInputElem, mapWrapID) {
        console.log(locationInputElem); // django widget textarea widget (hidden)
        console.log(lat, lng);  // deleted marker coordinates
        console.log(mapWrapID); // map widget wrapper element ID
});
```
