### ISSUE TITLE
Incompatibility with Django 2.1

### ISSUE THREAD

**Issue by joshsweaney** [erdem/django-map-widgets#76]
Getting this error for all widgets.
TypeError: render () got an unexpected keyword argument 'renderer'

Django 2.1 release says, Feature removed in 2.1:
"Support for Widget.render ( ) methods without the renderer argument is removed. "

Adding renderer=None to all widget methods in widgets.py solves this problem.

**Comment by joshsweaney** [comment]
Just realised there's already a pull request for this (#75 ). Never mind! Be great if that could be approved ASAP.

**Comment by erdem** [comment]
The PR just merged.
