### ISSUE TITLE
Fails render on Django 2.1

### ISSUE THREAD

**Issue by avdata99** [erdem/django-map-widgets#77]
I updated to django 2.1 and get some error
![seleccion_0788](https://user-images.githubusercontent.com/3237309/44370027-e8b15280-a4ae-11e8-99a7-f929564c23cc.png)

I think is because the _rendered_ param: https://docs.djangoproject.com/es/2.1/releases/2.1/#features-removed-in-2-1

**Comment by avdata99** [comment]
[This](https://github.com/erdem/django-map-widgets/commit/67129589c3ce08d9ad62aa9a9b5a6844e3f15332) fixes this.

**Comment by kornikopic** [comment]
@avdata99  How do I update the package? The version is still 0.1.9.

**Comment by avdata99** [comment]
Change you _requeriments.txt_ like that:
![image](https://user-images.githubusercontent.com/3237309/44487100-c2fd8800-a62b-11e8-9c08-09c6e21f9410.png)

Point to:
-e git://github.com/erdem/django-map-widgets.git@67129589c3ce08d9ad62aa9a9b5a6844e3f15332#egg=django-map-widgets

**Comment by kornikopic** [comment]
@avdata99 Thanks. I was afraid of this solution.

@erdem do you mind to create a release? It will be easier for the others to install/update the package.

**Comment by avdata99** [comment]
Don't be afraid @kornikopic is the same thing if Erdem publish this commit as 2.0 versión.

**Comment by erdem** [comment]
@kornikopic I tried to create a new release yesterday, but I didn't publish the release. There are some updates on PyPy API. The project setup.py not compatible anymore. I will look into it again. 

@avdata99 Thanks for the update.

**Comment by kornikopic** [comment]
@avdata99 Sorry but I disagree with you. If someone install the package, he won't get your fix. He will have to find this post so he can update to your latest commit. That's why I'm suggesting him to publish a release so everyone can enjoy your fix :)

**Comment by kornikopic** [comment]
Hi @erdem, any updates for the next release ? Thank you.

**Comment by erdem** [comment]
Hi @kornikopic 

I am still working on `v0.2.0_pre_release` branch. I am planning to fix https://github.com/erdem/django-map-widgets/issues/74 first then ready to go PyPI. Possible I will push the release in this week. 

The current pre-release branch on the test PyPI host. So, would be good if you can install the test release on your project then give us some feedback after testing. 

`pip install --index-url https://test.pypi.org/simple/ django-map-widgets==0.2.0`

Thanks.

**Comment by kornikopic** [comment]
Hi @erdem,

Thank you for the feedback. Awesome! I installed the pre-release. I'll let you know if there's anything. So far, it's working.

**Comment by erdem** [comment]
Hi @avdata99 

I released version `0.2.0`, you can install from live PyPI now. 

Thanks!
