### ISSUE TITLE
I place the parameter returns undefined by dragging the marker.

### ISSUE THREAD

**Issue by felocru** [erdem/django-map-widgets#81]
Hi, when I drag the markup on the map it returns undefined the place parameter. But this does not happen when I write in the search field. The place parameter contains address information.
Do you know what could be happening?

**Comment by felocru** [comment]
I did my debugging tests, and apparently the first event is executed: google_point_map_widget: place_changed, and then the method is executed: callPlaceTriggerHandler.
However, I notice that there is a trigger to execute the event, but it never executes again.

**Comment by felocru** [comment]
Hello again. I was reviewing the documentation and this event: google_point_map_widget: place_changed is not found in the documentation. This is the event that does work in all scenarios. When the marker is dragged, it is moved after the user wrote in the field, among others.
It would be good to enter this event in the documentation.

**Comment by erdem** [comment]
Thank you for notice @felocru. I added to the ToDo.
