### ISSUE TITLE
Google Terrain

### ISSUE THREAD

**Issue by natalie-poulson** [erdem/django-map-widgets#82]
Hello, 

Is there a way to display the map as terrain only? Or atleast terrain by default?

Thank you,
Natalie

**Comment by erdem** [comment]
Hello @natalie-poulson 

Unfournetly, there is no way to display the map as terrain with PyPI package. The package doesn't support custom map settings at the moment. 

You can change the map layer type if you fork the project. I am assuming you need to pass `mapTypeId: 'satellite'` parameter to Google `Map` class here;

https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/static/mapwidgets/js/mw_google_point_field.js#L21

I happy to merge your pull-request if you implement this feature as a settings option. :)

Thanks

**Comment by erdem** [comment]
@natalie-poulson btw, you might do something with google JS map object.  You can reach the object with `JQuery.data`. 

`$('.mw-map).data('google-map')`

Check this PR for more usage. 
https://github.com/erdem/django-map-widgets/issues/62
