### ISSUE TITLE
OpenStreetMap example?  

### ISSUE THREAD

**Issue by ursomniac** [erdem/django-map-widgets#86]
Does this only work for Google Maps ($$$)?   If so could you remove the references to OpenStreetMap?   Otherwise, provide an example using that.   Thanks.,

**Comment by erdem** [comment]
There is no OpenStreetMap reference anywhere in the document or readme file. I mentioned in  `Achievements` section as an example major service name.

**Comment by JackMorganNZ** [comment]
Hi @erdem, there is still several references to OpenStreetMap on your website, including the top of the README.

Occurrences are here: https://github.com/erdem/django-map-widgets/search?q=OpenStreetMap&unscoped_q=OpenStreetMap
