### ISSUE TITLE
How to populate address field in database ?

### ISSUE THREAD

**Issue by Arti3DPlayer** [erdem/django-map-widgets#89]
![screen shot 2018-12-14 at 13 24 40](https://user-images.githubusercontent.com/3278913/50000888-ac48bb80-ffa3-11e8-9b4d-31e70a398240.png)

Is there a way to populate address ?

**Comment by dennishylau** [comment]
Do you mean you want to do reverse geocoding on the pinned coordinate? Check out the docs of Google Maps API for that

**Comment by Arti3DPlayer** [comment]
@dennishylau No, as you see on screenshot I have another address field which I want to hide and populate from here:

<img width="168" alt="screen shot 2019-02-24 at 14 34 36" src="https://user-images.githubusercontent.com/3278913/53297238-5fa21c00-3841-11e9-88a0-cb0d77ea9497.png">

Ok, then I need custom js to handle this. Thank you

**Comment by erdem** [comment]
https://django-map-widgets.readthedocs.io/en/latest/widgets/point_field_map_widgets.html#javascript-triggers

**Comment by masavini** [comment]
> @dennishylau No, as you see on screenshot I have another address field which I want to hide and populate from here:
> 
> <img alt="screen shot 2019-02-24 at 14 34 36" width="168" src="https://user-images.githubusercontent.com/3278913/53297238-5fa21c00-3841-11e9-88a0-cb0d77ea9497.png">
> 
> Ok, then I need custom js to handle this. Thank you

@dennishylau, may i ask you how did you solve this? i have the same exact issue...
