### ISSUE TITLE
Suggestion: use widgets without geodjango

### ISSUE THREAD

**Issue by drakkan** [erdem/django-map-widgets#90]
Maybe this is out of the scope for this project, anyway could be useful to use the widgets without geodjango, for example Google Map Point Field Widget could be used inside admin to let the users pick a position. Actually the position is stored inside models.PointField it could be store for example as json inside a textfield using a model field provided by this library.

I was searching for a widget to pick position from map, this seems one of the most curated but I don't want to add a spatial database to my app only to pick lat/long from map.

Please close if out of scope, thanks!

**Comment by erdem** [comment]
Hi @drakkan 

Sorry for delayed response, I just saw this feedback. 

It's actually a good idea, but it must be in a different repo though. This package build for only Django. The other thing is, I can't separate too much time to this project anymore. I am trying to keep stable current widgets. If you or someone can remove GeoDjango dependency in a different repo, I am happy to put readme file as reference. 

Thanks
