### ISSUE TITLE
Google Api Key

### ISSUE THREAD

**Issue by atulmishra-one** [erdem/django-map-widgets#91]
The Map is not working. Please add a way to add API_KEY in setttings

**Comment by wassim6** [comment]
Check this doc: https://github.com/erdem/django-map-widgets/blob/5db0652640c404223142c00224cd83dd9bd0a9e4/docs/widgets/google_static_map_widget.rst

In your settings.py file, add your MAP_WIDGETS config:

```
MAP_WIDGETS = {
    "GoogleStaticMapWidget": (
        ("zoom", 15),
        ("size", "320x320"),
    ),
    "GoogleStaticMapMarkerSettings": (
        ("color", "green"),
    ),
    "GOOGLE_MAP_API_KEY": "<google-map-api-key>"
}
```
