### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement

### ISSUE THREAD

**Issue by pauloscardine** [erdem/django-map-widgets#96]
According to this [answer in stackoverflow](https://stackoverflow.com/questions/34063439/invalidvalueerror-not-an-instance-of-htmlinputelement) the newer version of the google maps API needs an HTML input element instead of a textarea.

> Your field is TEXTAREA, and from last updates, google maps autocomplete now supports only window.HTMLInputElement (INPUT tag)

**Comment by erdem** [comment]
Thank you for the notice @pauloscardine, the widget place autocompletes implementation using HTML text input already.  

https://github.com/erdem/django-map-widgets/blob/master/mapwidgets/templates/mapwidgets/google-point-field-widget.html#L25

**Comment by pauloscardine** [comment]
Yeah, my bad, I was overriding the template in an old project and my local changes were based on the old version. Sorry for the false alarm.
