### ISSUE TITLE
Feature Request: Mapbox Support

### ISSUE THREAD

**Issue by efe** [erdem/django-map-widgets#97]
Hello,

Google Maps API costs at least $5/monthly for Geocode or Geolocation. [[source]](https://cloud.google.com/maps-platform/pricing/sheet/) On the other hand, Mapbox provides generous free tier. [Map loads](https://www.mapbox.com/pricing/#maps) are free up to 50,000. [Geocoding](https://www.mapbox.com/pricing/#geocode) is free up to 100,000 requests.

Therefore, Mapbox would be a better choice for small projects. I'd like to contribute Mapbox support for this package. @erdem What do you think about it?

**Comment by erdem** [comment]
Hi @efe 

As I told you when we meet, new contributions are always welcome for this project. When you need help with this, I am happy to guide you.

Thanks

**Comment by janbaykara** [comment]
I've added a contribution towards this at #126
